{
 "title": "Celeborn",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(metrics_JVMCPUTime_Value, instance)"
    }
   },
   { "name": "baseLegend", "label": "baseLegend", "query": "__auto" }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_RegisteredShuffleCount_Value",
     "type": "timeseries",
     "description": "The count of registered shuffle.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "metrics_RegisteredShuffleCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_AvailableWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in available list.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "metrics_AvailableWorkerCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornTotalBytes_Value",
     "type": "timeseries",
     "description": "Celeborn total device capacity.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornTotalBytes_Value{role=\"Master\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornFreeBytes_Value",
     "type": "timeseries",
     "description": "Celeborn total device free capacity.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornFreeBytes_Value{role=\"Master\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_RunningApplicationCount_Value",
     "type": "timeseries",
     "description": "The count of running applications.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "metrics_RunningApplicationCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_IsActiveMaster_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_IsActiveMaster_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PartitionSize_Value",
     "type": "timeseries",
     "description": "The size of estimated shuffle partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_PartitionSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ShutdownWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in shutdown list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "metrics_ShutdownWorkerCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleFileCount_Value",
     "type": "timeseries",
     "description": "The active shuffle file count of workers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleFileCount_Value{role=\"Master\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleSize_Value",
     "type": "timeseries",
     "description": "The active shuffle size of workers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleSize_Value{role=\"Master\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OfferSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_OfferSlotsTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OfferSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_OfferSlotsTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ExcludedWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in excluded list.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "metrics_ExcludedWorkerCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WorkerCount_Value",
     "type": "timeseries",
     "description": "The count of active workers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "metrics_WorkerCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_LostWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in lost list.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "metrics_LostWorkerCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ShuffleTotalCount_Value",
     "type": "timeseries",
     "description": "The total count of shuffle including celeborn shuffle and spark built-in shuffle.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "metrics_ShuffleTotalCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ShuffleFallbackCount_Value",
     "type": "timeseries",
     "description": "The count of shuffle fallbacks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "metrics_ShuffleFallbackCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SlotsAllocated_increase_1h",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "increase(metrics_SlotsAllocated_Count{instance=~\"${instance}\"}[1h])",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReserveSlotsTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReserveSlotsTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PausePushData_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "metrics_PausePushData_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PausePushDataAndReplicate_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "metrics_PausePushDataAndReplicate_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PausePushDataTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PausePushDataTime_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PausePushDataAndReplicateTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PausePushDataAndReplicateTime_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleSize_Value",
     "type": "timeseries",
     "description": "The active shuffle size of a worker including master replica and slave replica.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleSize_Value{role=\"Worker\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleFileCount_Value",
     "type": "timeseries",
     "description": "The active shuffle file count of a worker including master replica and slave replica.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleFileCount_Value{role=\"Worker\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveConnectionCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "metrics_ActiveConnectionCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveSlotsCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "metrics_ActiveSlotsCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FlushWorkingQueueSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "metrics_FlushWorkingQueueSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_UnreleasedShuffleCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "metrics_UnreleasedShuffleCount_Value"
      }
     ]
    },
    {
     "title": "metrics_IsDecommissioningWorker_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "metrics_IsDecommissioningWorker_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "PushRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PrimaryPushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryPushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WriteDataSuccessCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "metrics_WriteDataSuccessCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WriteDataFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "metrics_WriteDataFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataWriteFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataWriteFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataCreateConnectionFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataCreateConnectionFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataConnectionExceptionCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataConnectionExceptionCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataTimeoutCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataTimeoutCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataFailNonCriticalCauseCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataFailNonCriticalCauseCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WriteDataHardSplitCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "metrics_WriteDataHardSplitCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "FetchRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_OpenStreamTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_OpenStreamTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OpenStreamTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_OpenStreamTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_FetchChunkTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_FetchChunkTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OpenStreamSuccessCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "metrics_OpenStreamSuccessCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OpenStreamFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "metrics_OpenStreamFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkSuccessCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "metrics_FetchChunkSuccessCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "metrics_FetchChunkFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveChunkStreamCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "metrics_ActiveChunkStreamCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTransferSize_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "metrics_FetchChunkTransferSize_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTransferSize_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_FetchChunkTransferSize_Max{role=\"Master\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTransferSize_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_FetchChunkTransferSize_Mean{role=\"Master\", instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTransferTime_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "metrics_FetchChunkTransferTime_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTransferTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_FetchChunkTransferTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkTransferTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_FetchChunkTransferTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "FlushDataRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_TakeBufferTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_TakeBufferTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_TakeBufferTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_TakeBufferTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_FlushDataTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_FlushDataTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_CommitFilesTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_CommitFilesTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_CommitFilesTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_CommitFilesTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "MemoryRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_NettyMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_NettyMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "DirectMemoryUsageRatio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "metrics_DirectMemoryUsageRatio_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "MemoryFileStorageSize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_MemoryFileStorageSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "MemoryStorageFileCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "metrics_MemoryStorageFileCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DiskBuffer_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_DiskBuffer_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "EvictedFileCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "metrics_EvictedFileCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_push_usedHeapMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_push_usedDirectMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_numHeapArenas_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "metrics_push_numHeapArenas_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_numDirectArenas_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "metrics_push_numDirectArenas_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_tinyCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "metrics_push_tinyCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_smallCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "metrics_push_smallCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_normalCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "metrics_push_normalCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_numThreadLocalCaches_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "metrics_push_numThreadLocalCaches_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_chunkSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "metrics_push_chunkSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_fetch_usedHeapMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_fetch_usedDirectMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_numHeapArenas_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "metrics_fetch_numHeapArenas_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_numDirectArenas_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "metrics_fetch_numDirectArenas_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_tinyCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "metrics_fetch_tinyCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_smallCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "metrics_fetch_smallCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_normalCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "targets": [
      {
       "expr": "metrics_fetch_normalCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_numThreadLocalCaches_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "metrics_fetch_numThreadLocalCaches_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_chunkSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "metrics_fetch_chunkSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_replicate_usedHeapMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_replicate_usedDirectMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_numHeapArenas_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "metrics_replicate_numHeapArenas_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_numDirectArenas_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "metrics_replicate_numDirectArenas_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_tinyCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "metrics_replicate_tinyCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_smallCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "metrics_replicate_smallCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_normalCacheSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "metrics_replicate_normalCacheSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_numThreadLocalCaches_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "expr": "metrics_replicate_numThreadLocalCaches_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_chunkSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "metrics_replicate_chunkSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "ReadBufferAllocatedCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "targets": [
      {
       "expr": "metrics_ReadBufferAllocatedCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "BufferStreamReadBuffer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_BufferStreamReadBuffer_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "ReadBufferDispatcherRequestsLength",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "expr": "metrics_ReadBufferDispatcherRequestsLength_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "SortRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SortTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 885 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_SortTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_SortTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 885 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_SortTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_SortingFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 893 },
     "targets": [
      {
       "expr": "metrics_SortingFiles_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_SortedFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 893 },
     "targets": [
      {
       "expr": "metrics_SortedFiles_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_SortMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 901 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_SortMemory_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_SortedFileSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 901 },
     "targets": [
      {
       "expr": "metrics_SortedFileSize_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "CongestionRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PotentialConsumeSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 910 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "metrics_PotentialConsumeSpeed_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WorkerConsumeSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 910 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "metrics_WorkerConsumeSpeed_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_UserProduceSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 918 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "metrics_UserProduceSpeed_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "MapPartitionRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PrimaryPushDataHandshakeTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 593 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataHandshakeTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryPushDataHandshakeTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 593 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataHandshakeTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataHandshakeTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 666 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataHandshakeTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataHandshakeTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 666 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataHandshakeTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 675 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionStartTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 675 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionStartTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 684 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionStartTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 684 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionStartTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionFinishTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 693 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionFinishTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionFinishTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 693 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionFinishTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionFinishTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 702 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionFinishTime_Mean{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionFinishTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 702 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionFinishTime_Max{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PushDataHandshakeFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 711 },
     "targets": [
      {
       "expr": "metrics_PushDataHandshakeFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_RegionStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 711 },
     "targets": [
      {
       "expr": "metrics_RegionStartFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_RegionStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 719 },
     "targets": [
      {
       "expr": "metrics_RegionStartFailCount_Count{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_SegmentStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 719 },
     "targets": [
      {
       "expr": "metrics_SegmentStartFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaSegmentStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 727 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaSegmentStartTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaSegmentStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 727 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaSegmentStartTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimarySegmentStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 736 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimarySegmentStartTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimarySegmentStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 736 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimarySegmentStartTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "Credit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "ActiveCreditStreamCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 998 },
     "targets": [
      {
       "expr": "metrics_ActiveCreditStreamCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "ActiveMapPartitionCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 998 },
     "targets": [
      {
       "expr": "metrics_ActiveMapPartitionCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_JVMCPUTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1007 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "metrics_JVMCPUTime_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_LastMinuteSystemLoad_Value",
     "type": "timeseries",
     "description": "The system load average for the last minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1007 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_LastMinuteSystemLoad_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceOSFreeBytes_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1015 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceOSFreeBytes_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornFreeBytes_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1015 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornFreeBytes_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_AvailableProcessors_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1023 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_AvailableProcessors_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "UserConsumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_diskFileCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1032 },
     "targets": [
      {
       "expr": "metrics_diskFileCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_diskBytesWritten_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1032 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_diskBytesWritten_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_hdfsFileCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1041 },
     "targets": [
      {
       "expr": "metrics_hdfsFileCount_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_hdfsBytesWritten_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1041 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_hdfsBytesWritten_Value{instance=~\"${instance}\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  }
 ]
}